ZSH_THEME="eastwood"

export UPDATE_ZSH_DAYS=1

DISABLE_UNTRACKED_FILES_DIRTY="true"
plugins=(
  git
  ubuntu
  nmap
  golang
  zsh-syntax-highlighting
  python
  pyenv
  pylint
)

export PATH=$PATH:/$HOME/.pyenv/bin:/usr/local/go/bin
export PATH=$PATH:$HOME/.local/bin:$HOME/go/bin/:$HOME/.tfenv/bin:/usr/games
export PYENV_ROOT="$HOME/.pyenv/shims"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
eval "$(pyenv virtualenv-init -)"

source $HOME/.oh-my-zsh/oh-my-zsh.sh

export GPG_TTY=$(tty)
export VISUAL=/usr/bin/vim

EDITOR='vim'

export RIPGREP_CONFIG_PATH=$HOME/.ripgreprc
export FZF_DEFAULT_COMMAND='rg -l ""'

export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] \
  && printf %s "${HOME}/.nvm" \
  || printf %s "${XDG_CONFIG_HOME}/nvm")"

[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
