name: ci

on:
  push:
    branches: main

jobs:
  build:
    name: Run build

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@master
      with:
        ref: ${{ github.ref }}

    - name: Check out
      run: |

        ls -hlaR

    - name: Run scam
      run: |

        bash salus.sh

